# Generated by Django 5.1.1 on 2024-10-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payments_identificador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='identificador',
            new_name='identifier',
        ),
    ]
